name: Build macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Build
        working-directory: src
        env:
          PYTHON_V: '3.13'
          MACOSX_DEPLOYMENT_TARGET: '13.0'
        run: pyinstaller --noconfirm artisan-mac.spec

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: artisan-mac-dmg
          path: src/artisan-mac-*.dmg
